---
title: "Part_1_Sea_ice"
author: "Heyue WU_u7628175"
date: "15/09/2023"
output:  
    html_document:
        toc: true
        toc_depth: 4
        theme: cosmo
        number_sections: false
        toc_float: true
        highlight: pygments
        fig_width: 8
        fig_height: 4
---

# Location on GitHub

https://github.com/AdriaWu/DS4B-short-report-1//blob/main/DS4B-short-report-1/Part_1_Sea_ice.Rmd

# 1. Loading the data_1 and preparing for the packages

```{r}
# Load necessary R packages
library(tidyverse)
library(ggplot2)
library(readxl)
library(dplyr)
library(lubridate)

# Read data from Excel file
data_1 <- read_csv("raw_data/S_seaice_extent_daily_v3.0.csv")

# have a quick view of the data
tibble(data_1)

# Check the type of value
summary(data_1)
```

# 2. Data Transformation

```{r}
# Delete the second row of data
data_1 <- data_1 |>
  slice(-1)

# Transform some columns to numbers in order to calculate or plot
data_1$Extent <- as.numeric(as.character(data_1$Extent))
data_1$Year <- as.numeric(as.character(data_1$Year))

# Check the tidy_data
tibble(data_1)
```

# 3. Filter data and evaluate by year or month

```{r}
# Filter out the data for winter
winter_data <- data_1 |>
  filter(Month %in% c(6, 7, 8))

Jun_df<- winter_data |>
  filter(Month == 6) |>
  group_by(Year) |>
  summarise(
    Mean_Jun_Extent = mean(Extent, na.rm = TRUE)
    )

July_df <- winter_data |>
  filter(Month == 7) |>
  group_by(Year) |>
  summarise(
    Mean_July_Extent = mean(Extent, na.rm = TRUE)
    )

Aug_df <- winter_data |>
  filter(Month == 8) |>
  group_by(Year) |>
  summarise(
    Mean_Aug_Extent = mean(Extent, na.rm = TRUE)
    )

Year_df <- winter_data |>
  group_by(Year) |>
  summarise(
    Min_Winter_Extent = min(Extent, na.rm = TRUE),
    Mean_Winter_Extent = mean(Extent, na.rm = TRUE),
    .groups = "drop"
  )

# Merge the data frames

# Merge Jun_df and July_df
merged_df <- left_join(Jun_df, July_df, by = "Year")

# Merge merged_df and Aug_df
merged_df <- left_join(merged_df, Aug_df, by = "Year")

# Merge merged_df and Year_df
final_df <- left_join(merged_df, Year_df, by = "Year")

# Check the results
print(Jun_df)
print(July_df)
print(Aug_df)
print(Year_df)
print(final_df)

```

# 4. Use ggplot to plot the time series

```{r}
plot_1 <- ggplot(final_df, aes(x = Year)) +
  geom_line(aes(y = Mean_Jun_Extent, color = "Mean_Jun_Extent")) +
  geom_line(aes(y = Mean_July_Extent, color = "Mean_July_Extent")) +
  geom_line(aes(y = Mean_Aug_Extent, color = "Mean_Aug_Extent")) +
  geom_line(aes(y = Min_Winter_Extent, color = "Min_Winter_Extent"), linetype = "dashed") +
  geom_line(aes(y = Mean_Winter_Extent, color = "Mean_Winter_Extent"), linetype = "dashed") +
  labs(y = "Extent", color = "Legend") +
  scale_x_continuous(breaks = seq(min(final_df$Year), max(final_df$Year), by = 2)) +
  # Rotate x-axis label 90 degrees
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme_minimal() 

plot_1
```











